eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice: 
  pay-service:
    endpoints: 
      endpoint:
        createtxn: http://PAY-SERVICE/pay/createtxn
  order-service:
    endpoints: 
      endpoint:
        fetch: http://ORDER-SERVICE/orders/fetch
        updpending: http://ORDER-SERVICE/orders/update/{orderId}/Pending
        updcomplete: http://ORDER-SERVICE/orders/update/{orderId}/Completed
 
